# This rule is not used by the project helm-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over helm-operator.ketches.cn.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: helm-operator
    app.kubernetes.io/managed-by: kustomize
  name: helmrelease-admin-role
rules:
- apiGroups:
  - helm-operator.ketches.cn
  resources:
  - helmreleases
  verbs:
  - '*'
- apiGroups:
  - helm-operator.ketches.cn
  resources:
  - helmreleases/status
  verbs:
  - get
