// This file is auto-generated by scripts/generate-resources.sh
// DO NOT EDIT MANUALLY

// resources contains all the YAML manifests for helm-operator installation

package installer

var resources = []string{
	`
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: helmreleases.helm-operator.ketches.cn
spec:
  group: helm-operator.ketches.cn
  names:
    kind: HelmRelease
    listKind: HelmReleaseList
    plural: helmreleases
    singular: helmrelease
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.chart.name
      name: Chart
      type: string
    - jsonPath: .spec.chart.version
      name: Version
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].message
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HelmRelease is the Schema for the helmreleases API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: HelmReleaseSpec defines the desired state of HelmRelease.
            properties:
              chart:
                description: Chart specifies the chart information
                properties:
                  name:
                    description: Name of the chart
                    minLength: 1
                    type: string
                  repository:
                    description: Repository contains repository reference
                    properties:
                      name:
                        description: Name of the HelmRepository
                        type: string
                      namespace:
                        description: Namespace of the HelmRepository
                        type: string
                    required:
                    - name
                    type: object
                  repositoryURL:
                    description: RepositoryURL is the direct URL to the repository
                    type: string
                  version:
                    description: Version of the chart
                    type: string
                required:
                - name
                type: object
              dependsOn:
                description: DependsOn contains references to other releases this
                  release depends on
                items:
                  description: DependencyReference contains reference to a dependency
                  properties:
                    name:
                      description: Name of the dependency release
                      type: string
                    namespace:
                      description: Namespace of the dependency release
                      type: string
                  required:
                  - name
                  type: object
                type: array
              install:
                description: Install contains installation configuration
                properties:
                  disableHooks:
                    default: false
                    description: DisableHooks indicates whether to disable hooks
                    type: boolean
                  replace:
                    default: false
                    description: Replace indicates whether to replace existing resources
                    type: boolean
                  skipCRDs:
                    default: false
                    description: SkipCRDs indicates whether to skip CRD installation
                    type: boolean
                  timeout:
                    default: 10m
                    description: Timeout for the install operation
                    pattern: ^([0-9]+(\\.[0-9]+)?(ms|s|m|h))+$
                    type: string
                  wait:
                    default: true
                    description: Wait indicates whether to wait for the installation
                      to complete
                    type: boolean
                  waitForJobs:
                    default: true
                    description: WaitForJobs indicates whether to wait for jobs to
                      complete
                    type: boolean
                type: object
              interval:
                description: Interval specifies how often to reconcile the release
                pattern: ^([0-9]+(\\.[0-9]+)?(ms|s|m|h))+$
                type: string
              release:
                description: Release contains release configuration
                properties:
                  createNamespace:
                    default: false
                    description: CreateNamespace indicates whether to create the namespace
                      if it doesn't exist
                    type: boolean
                  name:
                    description: Name of the release
                    type: string
                  namespace:
                    description: Namespace where the release will be installed
                    type: string
                type: object
              suspend:
                default: false
                description: Suspend tells the controller to suspend subsequent reconciliations
                type: boolean
              uninstall:
                description: Uninstall contains uninstallation configuration
                properties:
                  disableHooks:
                    default: false
                    description: DisableHooks indicates whether to disable hooks
                    type: boolean
                  keepHistory:
                    default: false
                    description: KeepHistory indicates whether to keep release history
                    type: boolean
                  timeout:
                    default: 5m
                    description: Timeout for the uninstall operation
                    pattern: ^([0-9]+(\\.[0-9]+)?(ms|s|m|h))+$
                    type: string
                type: object
              upgrade:
                description: Upgrade contains upgrade configuration
                properties:
                  cleanupOnFail:
                    default: true
                    description: CleanupOnFail indicates whether to cleanup on failure
                    type: boolean
                  disableHooks:
                    default: false
                    description: DisableHooks indicates whether to disable hooks
                    type: boolean
                  force:
                    default: false
                    description: Force indicates whether to force upgrade
                    type: boolean
                  maxHistory:
                    default: 10
                    description: MaxHistory limits the maximum number of revisions
                      saved per release
                    type: integer
                  recreate:
                    default: false
                    description: Recreate indicates whether to recreate resources
                    type: boolean
                  resetValues:
                    default: false
                    description: ResetValues indicates whether to reset values to
                      chart defaults
                    type: boolean
                  reuseValues:
                    default: false
                    description: ReuseValues indicates whether to reuse existing values
                    type: boolean
                  timeout:
                    default: 10m
                    description: Timeout for the upgrade operation
                    pattern: ^([0-9]+(\\.[0-9]+)?(ms|s|m|h))+$
                    type: string
                  wait:
                    default: true
                    description: Wait indicates whether to wait for the upgrade to
                      complete
                    type: boolean
                  waitForJobs:
                    default: true
                    description: WaitForJobs indicates whether to wait for jobs to
                      complete
                    type: boolean
                type: object
              values:
                description: Values contains custom values for the chart as YAML string
                type: string
            required:
            - chart
            type: object
          status:
            description: HelmReleaseStatus defines the observed state of HelmRelease.
            properties:
              conditions:
                description: Conditions contains the different condition statuses
                  for this release
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              failures:
                description: Failures contains information about failed operations
                items:
                  description: FailureRecord contains information about a failed operation
                  properties:
                    message:
                      description: Message describing the failure
                      type: string
                    reason:
                      description: Reason for the failure
                      type: string
                    time:
                      description: Time when the failure occurred
                      format: date-time
                      type: string
                  required:
                  - message
                  - reason
                  - time
                  type: object
                type: array
              helmRelease:
                description: HelmRelease contains information about the Helm release
                properties:
                  appVersion:
                    description: AppVersion of the application
                    type: string
                  chart:
                    description: Chart name and version
                    type: string
                  description:
                    description: Description of the release
                    type: string
                  firstDeployed:
                    description: FirstDeployed timestamp
                    format: date-time
                    type: string
                  lastDeployed:
                    description: LastDeployed timestamp
                    format: date-time
                    type: string
                  name:
                    description: Name of the release
                    type: string
                  namespace:
                    description: Namespace of the release
                    type: string
                  revision:
                    description: Revision of the release
                    type: integer
                  status:
                    description: Status of the release
                    type: string
                required:
                - name
                - namespace
                - revision
                - status
                type: object
              lastAppliedConfiguration:
                description: LastAppliedConfiguration contains the last applied configuration
                properties:
                  chart:
                    description: Chart specifies the chart information
                    properties:
                      name:
                        description: Name of the chart
                        minLength: 1
                        type: string
                      repository:
                        description: Repository contains repository reference
                        properties:
                          name:
                            description: Name of the HelmRepository
                            type: string
                          namespace:
                            description: Namespace of the HelmRepository
                            type: string
                        required:
                        - name
                        type: object
                      repositoryURL:
                        description: RepositoryURL is the direct URL to the repository
                        type: string
                      version:
                        description: Version of the chart
                        type: string
                    required:
                    - name
                    type: object
                  dependsOn:
                    description: DependsOn contains references to other releases this
                      release depends on
                    items:
                      description: DependencyReference contains reference to a dependency
                      properties:
                        name:
                          description: Name of the dependency release
                          type: string
                        namespace:
                          description: Namespace of the dependency release
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                  install:
                    description: Install contains installation configuration
                    properties:
                      disableHooks:
                        default: false
                        description: DisableHooks indicates whether to disable hooks
                        type: boolean
                      replace:
                        default: false
                        description: Replace indicates whether to replace existing
                          resources
                        type: boolean
                      skipCRDs:
                        default: false
                        description: SkipCRDs indicates whether to skip CRD installation
                        type: boolean
                      timeout:
                        default: 10m
                        description: Timeout for the install operation
                        pattern: ^([0-9]+(\\.[0-9]+)?(ms|s|m|h))+$
                        type: string
                      wait:
                        default: true
                        description: Wait indicates whether to wait for the installation
                          to complete
                        type: boolean
                      waitForJobs:
                        default: true
                        description: WaitForJobs indicates whether to wait for jobs
                          to complete
                        type: boolean
                    type: object
                  interval:
                    description: Interval specifies how often to reconcile the release
                    pattern: ^([0-9]+(\\.[0-9]+)?(ms|s|m|h))+$
                    type: string
                  release:
                    description: Release contains release configuration
                    properties:
                      createNamespace:
                        default: false
                        description: CreateNamespace indicates whether to create the
                          namespace if it doesn't exist
                        type: boolean
                      name:
                        description: Name of the release
                        type: string
                      namespace:
                        description: Namespace where the release will be installed
                        type: string
                    type: object
                  suspend:
                    default: false
                    description: Suspend tells the controller to suspend subsequent
                      reconciliations
                    type: boolean
                  uninstall:
                    description: Uninstall contains uninstallation configuration
                    properties:
                      disableHooks:
                        default: false
                        description: DisableHooks indicates whether to disable hooks
                        type: boolean
                      keepHistory:
                        default: false
                        description: KeepHistory indicates whether to keep release
                          history
                        type: boolean
                      timeout:
                        default: 5m
                        description: Timeout for the uninstall operation
                        pattern: ^([0-9]+(\\.[0-9]+)?(ms|s|m|h))+$
                        type: string
                    type: object
                  upgrade:
                    description: Upgrade contains upgrade configuration
                    properties:
                      cleanupOnFail:
                        default: true
                        description: CleanupOnFail indicates whether to cleanup on
                          failure
                        type: boolean
                      disableHooks:
                        default: false
                        description: DisableHooks indicates whether to disable hooks
                        type: boolean
                      force:
                        default: false
                        description: Force indicates whether to force upgrade
                        type: boolean
                      maxHistory:
                        default: 10
                        description: MaxHistory limits the maximum number of revisions
                          saved per release
                        type: integer
                      recreate:
                        default: false
                        description: Recreate indicates whether to recreate resources
                        type: boolean
                      resetValues:
                        default: false
                        description: ResetValues indicates whether to reset values
                          to chart defaults
                        type: boolean
                      reuseValues:
                        default: false
                        description: ReuseValues indicates whether to reuse existing
                          values
                        type: boolean
                      timeout:
                        default: 10m
                        description: Timeout for the upgrade operation
                        pattern: ^([0-9]+(\\.[0-9]+)?(ms|s|m|h))+$
                        type: string
                      wait:
                        default: true
                        description: Wait indicates whether to wait for the upgrade
                          to complete
                        type: boolean
                      waitForJobs:
                        default: true
                        description: WaitForJobs indicates whether to wait for jobs
                          to complete
                        type: boolean
                    type: object
                  values:
                    description: Values contains custom values for the chart as YAML
                      string
                    type: string
                required:
                - chart
                type: object
              observedGeneration:
                description: ObservedGeneration is the last generation observed by
                  the controller
                format: int64
                type: integer
              originalValues:
                description: OriginalValues contains the default values from the chart
                  for comparison
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
`,
	`
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.18.0
  name: helmrepositories.helm-operator.ketches.cn
spec:
  group: helm-operator.ketches.cn
  names:
    kind: HelmRepository
    listKind: HelmRepositoryList
    plural: helmrepositories
    singular: helmrepository
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.url
      name: URL
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].status
      name: Ready
      type: string
    - jsonPath: .status.conditions[?(@.type=="Ready")].message
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: HelmRepository is the Schema for the helmrepositories API.
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: HelmRepositorySpec defines the desired state of HelmRepository.
            properties:
              auth:
                description: Auth contains authentication configuration
                properties:
                  basic:
                    description: Basic contains basic authentication configuration
                    properties:
                      password:
                        description: Password for basic authentication
                        type: string
                      secretRef:
                        description: SecretRef references a secret containing authentication
                          credentials
                        properties:
                          name:
                            description: Name of the secret
                            type: string
                          namespace:
                            description: Namespace of the secret
                            type: string
                        required:
                        - name
                        type: object
                      username:
                        description: Username for basic authentication
                        type: string
                    type: object
                  tls:
                    description: TLS contains TLS configuration
                    properties:
                      caFile:
                        description: CAFile path to CA certificate file
                        type: string
                      certFile:
                        description: CertFile path to client certificate file
                        type: string
                      insecureSkipVerify:
                        default: false
                        description: InsecureSkipVerify controls whether to skip TLS
                          certificate verification
                        type: boolean
                      keyFile:
                        description: KeyFile path to client private key file
                        type: string
                      secretRef:
                        description: SecretRef references a secret containing TLS
                          configuration
                        properties:
                          name:
                            description: Name of the secret
                            type: string
                          namespace:
                            description: Namespace of the secret
                            type: string
                        required:
                        - name
                        type: object
                    type: object
                type: object
              interval:
                default: 30m
                description: Interval specifies how often to sync the repository
                pattern: ^([0-9]+(\\.[0-9]+)?(ms|s|m|h))+$
                type: string
              suspend:
                default: false
                description: Suspend tells the controller to suspend subsequent sync
                  operations
                type: boolean
              timeout:
                default: 5m
                description: Timeout specifies the timeout for repository operations
                pattern: ^([0-9]+(\\.[0-9]+)?(ms|s|m|h))+$
                type: string
              type:
                default: helm
                description: Type specifies the repository type
                enum:
                - helm
                type: string
              url:
                description: URL is the repository URL
                minLength: 1
                pattern: ^(https?)://.*
                type: string
            required:
            - url
            type: object
          status:
            description: HelmRepositoryStatus defines the observed state of HelmRepository.
            properties:
              charts:
                description: Charts contains the list of charts found in the repository
                items:
                  description: ChartInfo contains information about a chart
                  properties:
                    description:
                      description: Description of the chart
                      type: string
                    name:
                      description: Name of the chart
                      type: string
                    versions:
                      description: Versions contains the list of chart versions
                      items:
                        description: ChartVersion contains information about a chart
                          version
                        properties:
                          appVersion:
                            description: AppVersion of the application
                            type: string
                          created:
                            description: Created timestamp
                            format: date-time
                            type: string
                          digest:
                            description: Digest of the chart
                            type: string
                          version:
                            description: Version of the chart
                            type: string
                        required:
                        - version
                        type: object
                      type: array
                  required:
                  - name
                  type: object
                type: array
              conditions:
                description: Conditions contains the different condition statuses
                  for this repository
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              lastSyncTime:
                description: LastSyncTime is the last time the repository was successfully
                  synced
                format: date-time
                type: string
              observedGeneration:
                description: ObservedGeneration is the last generation observed by
                  the controller
                format: int64
                type: integer
              stats:
                description: Stats contains repository statistics
                properties:
                  lastIndexSize:
                    description: LastIndexSize is the size of the last index file
                    type: string
                  totalCharts:
                    description: TotalCharts is the total number of charts
                    type: integer
                  totalVersions:
                    description: TotalVersions is the total number of chart versions
                    type: integer
                required:
                - totalCharts
                - totalVersions
                type: object
            type: object
        required:
        - metadata
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
`,
	`
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-operator
  namespace: ketches
  labels:
    ketches.cn/owned: "true"
    app.ketches.cn/name: helm-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-operator
  labels:
    ketches.cn/owned: "true"
    app.ketches.cn/name: helm-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: helm-operator
  namespace: ketches
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-operator
  namespace: ketches
  labels:
    ketches.cn/owned: "true"
    app.ketches.cn/name: helm-operator
spec:
  selector:
    matchLabels:
      app.ketches.cn/name: helm-operator
  replicas: 1
  template:
    metadata:
      labels:
        app.ketches.cn/name: helm-operator
    spec:
      containers:
      - args:
          - --leader-elect
        image: ketches/helm-operator:latest
        name: helm-operator
        ports: 
        - containerPort: 8081
          name: probe
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
      serviceAccountName: helm-operator
      terminationGracePeriodSeconds: 10`,
}
