apiVersion: helm-operator.ketches.cn/v1alpha1
kind: HelmRelease
metadata:
  labels:
    app.kubernetes.io/name: helm-operator
    app.kubernetes.io/managed-by: kustomize
  name: myapp-sample
  namespace: default
spec:
  chart:
    name: "myapp"
    version: "1.0.0"
    repository:
      name: "mycharts"
      namespace: "default"
  release:
    name: "myapp-sample-release"
    namespace: "default"
    createNamespace: true
  values: |
    replicaCount: 2
  install:
    timeout: "10m"
    wait: true
    waitForJobs: true
  upgrade:
    timeout: "10m"
    wait: true
    cleanupOnFail: true
  interval: "1h"
  suspend: false