# Example of private HTTP repository (internal network)
---
apiVersion: v1
kind: Secret
metadata:
  name: private-http-repo-auth
  namespace: default
type: Opaque
data:
  username: YWRtaW4=      # base64 encoded "admin"
  password: c2VjcmV0MTIz  # base64 encoded "secret123"
---
apiVersion: helm-operator.ketches.cn/v1alpha1
kind: HelmRepository
metadata:
  name: private-http-repo
  namespace: default
  labels:
    app.kubernetes.io/name: helm-operator
    app.kubernetes.io/managed-by: kustomize
spec:
  url: "http://internal-charts.company.local:8080"
  type: "helm"
  interval: "30m"
  timeout: "10m"
  auth:
    basic:
      secretRef:
        name: "private-http-repo-auth"
        namespace: "default"
    tls:
      insecureSkipVerify: true  # For HTTP repositories, this might be needed
  suspend: false