#!/bin/bash

# Script to generate resources.go from deploy directory
# This script reads all YAML files from deploy/ and embeds them as Go string literals

set -e

OUTPUT_FILE="pkg/installer/resources.go"
DEPLOY_DIR="deploy"

echo "Generating resources from $DEPLOY_DIR directory..."

# Start the Go file
cat > "$OUTPUT_FILE" << 'EOF'
// This file is auto-generated by scripts/generate-resources.sh
// DO NOT EDIT MANUALLY

// resources contains all the YAML manifests for helm-operator installation

package installer

var resources = []string{
EOF

# Function to escape Go string literals
escape_go_string() {
    # Escape backslashes and quotes for Go string literals
    sed 's/\\/\\\\/g; s/"/\\"/g; s/`/\\`/g'
}

# Process each YAML file in deploy directory
find "$DEPLOY_DIR" -name "*.yaml" -type f | sort | while read -r file; do
    echo "Processing $file..."
    
    # Add the file as a Go string literal
    echo "	\`" >> "$OUTPUT_FILE"
    
    # Read the file content and escape it for Go
    cat "$file" | escape_go_string >> "$OUTPUT_FILE"
    
    echo "\`," >> "$OUTPUT_FILE"
done

# Close the array
cat >> "$OUTPUT_FILE" << 'EOF'
}
EOF

echo "Generated $OUTPUT_FILE successfully"
echo "Found $(find "$DEPLOY_DIR" -name "*.yaml" -type f | wc -l) YAML files"